apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomized-hello

resources:
  - all.yaml

namePrefix: kustomized-

commonLabels:
  kustomized: "true"

patches:
  - path: patch.yaml
    target:
      kind: Deployment
